controller_manager_ns: controller_manager
controller_list:
  - name: sr_scara_hx/sr_scara_hx_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
